### ISSUE TITLE
Is Chinese pre-trained model available? 

### ISSUE THREAD

**Issue by LoneRanger0504** [imgarylai/bert-embedding#5]

**Comment by imgarylai** [comment]
Yes, it is. The implementation exists in gluonnlp. 
I added available lang in the [README.md](https://github.com/imgarylai/bert-embedding#available-pre-trained-bert-models)

However, since I have tested in English only, I'm not sure about would the output be expected as you want. Please test it out and let me know if there are anything to improve. PR are welcome! Thanks
